# Playbook that checks the health of the services.
#
# 1. Check databases replication used by the open edx platform:
# - MySQL DB
# - MongoDB
# - Elasticsearch
#
# 2. Run check urls for all the web servers
#
# Ansible playbook extra variables:
# - target_mysql_server - used to check only a subrange of MySQL databases for its health
# - target_mongo_server - used to change the default Mongo database instance where to check the health of the cluster
#
# Example:
#   ansible-playbook -i nau-data/envs/development/hosts.ini healthcheck.yml
#
---
- name: Run Makefile healthcheck
  hosts: all
  become: True
  gather_facts: True
  serial: "{{ serial_number | default(1) }}" # check in sequence
  tasks:
    - import_tasks: tasks/healthcheck.yml

- name: Check URLs
  hosts: all
  become: True
  gather_facts: True
  roles:
    - nau_check_urls
