# Update operating system packages and reboot the server if required.
# Optionally, you can only update, only reboot, or force a reboot, everything using
# a rolling approach.
# It changes the keepalived and iptables configuration during the update and the reboot.
#
# Inspired by:
# - https://luktom.net/en/e1497-how-to-update-centos-rhel-using-ansible
# - https://www.cyberciti.biz/faq/ansible-apt-update-all-packages-on-ubuntu-debian-linux/
#
# Example - update every server on inventory and reboot if needed:
#   ansible-playbook -i nau-data/envs/<>/hosts.ini update_and_reboot.yml
#
# Example - 
#   ansible-playbook -i nau-data/envs/<>/hosts.ini update_and_reboot.yml
---
- hosts: all
  serial: 1 # run update in sequence
  become: True
  gather_facts: True
  vars:
    close: false
    open: false
  pre_tasks:
    - name: Check if 'open' or 'close'
      assert:
        that: (open | bool) or (close | bool)
        fail_msg: You need to open or close
        quiet: true
    - import_tasks: tasks/close_node.yml
      when: (close|bool)
  tasks:
    - import_tasks: tasks/healthcheck.yml
      when: (open|bool)
  post_tasks:
    - import_tasks: tasks/open_node.yml
      when: (open|bool)
