---
- name: Backup Percona XtraDB Cluster with Percona XtraBackup
  hosts: xtradb_servers[-1]
  become: True
  gather_facts: True
  tasks:
    - name: Backup Percona XtraDB Cluster Database
      import_role:
        name: percona_xtrabackup
      vars:
        backup_mysql_login_user: root
        backup_mysql_login_password: "{{ xtradb_mysql_root_password }}"
