# Ansible playbook to export open edx database to excel with information on the Open edX LMS/Studio.
# It runs a git clone on the localhost machine, run a docker build, generates a configuration file and then runs the built docker image.
#
# Example:
#   ansible-playbook -i nau-data/envs/production/hosts.ini openedx_lms_db_export.yml -e "extra_params: -t"
#
#   ansible-playbook -i nau-data/envs/production/hosts.ini openedx_lms_db_export.yml -e nau_db_exporter_report_script=report_google.py -e nau_database_exporter_sheets_to_copy=organizations,course_runs,course_run_by_date,enrollments_year_of_birth,enrollments_gender,enrollments_level_of_education,enrollments_country,enrollments_employment_situation,registered_users_by_day,distinct_users_by_day,distinct_users_by_month,final_summary
---
- name: Exports information to excel from Open EDX LMS/Studio databases
  hosts: "staticproxy_docker_servers:&{{ target | default('staticproxy_docker_servers') }}[-1]"
  become: True
  gather_facts: True
  vars: 
    _nau_db_exporter_version: "{{ nau_db_exporter_version | default('master') }}"
    nau_db_exporter_extra_params: "{{ extra_params | default('') }}"
    nau_db_exporter_base_directory: /tmp/nau-database-exporter-{{ _nau_db_exporter_version }}
  
  tasks:
    - name: Create folder
      file:
        path: "{{ nau_db_exporter_base_directory }}"
        state: directory

    - name: Generates a configuration file
      template: 
        src: "{{ COMMON_PATH_CUSTOM_FILES }}/nau-database-exporter/config.ini.j2"
        dest: "{{ nau_db_exporter_base_directory }}/config.ini"

    - name: Pull docker image
      shell: docker pull nauedu/nau-database-exporter:{{ _nau_db_exporter_version }}

    - name: Runs the python the report script on a docker container
      shell: |
        docker run -t --rm \
        --name nau-database-exporter-{{ _nau_db_exporter_version }} \
        --mount type=bind,source={{ nau_db_exporter_base_directory }}/config.ini,target=/usr/src/app/config.ini \
        -v {{ nau_db_exporter_base_directory }}/output:/usr/src/app/output \
        nauedu/nau-database-exporter:{{ _nau_db_exporter_version }} \
        timeout 8h bash -c "python update_data.py {{ nau_db_exporter_extra_params }} && python {{ nau_db_exporter_report_script | default('report_xlsx.py') }} {{ nau_db_exporter_extra_params }}"
      args:
        chdir: "{{ nau_db_exporter_base_directory }}"
      register: sync_output

    - name: Print stdout of export output
      debug:
        msg: "{{ sync_output.stdout_lines }}"
      when: sync_output.stdout_lines is defined

    - name: Print stderr of export output
      debug:
        msg: "{{ sync_output.stderr_lines }}"
      when: sync_output.stderr_lines is defined
