# Run the pakiti client, but don't install it
# Pakiti is library that extracts some audit information on the server and sends its data to a pakiti server
#
# Example usage:
#   ansible-playbook -i nau-data/envs/<env>/hosts.ini pakiti.yml

---
- name: Runs the pakiti client
  hosts: all
  # ansible by default run parallel for every server, but we change this to run on synchronous mode.
  serial: "{{ serial_number | default(1) }}"
  # do not stop on the first error
  max_fail_percentage: "{{ max_fail_percentage | default(0) }}"
  become: True
  gather_facts: False
  roles: 
    - role: ansible_pakiti_client
      vars:
        pakiti_install: false # do not install the pakiti client because it should be installed using the deploy playbook
        pakiti_push: true # only run pakiti, not install it
