---
# Manage /etc/hosts file
- name: bertvv.hosts
  version: v1.2.0

# Install pip
- name: geerlingguy.pip
  version: 2.1.0

# Install docker
- name: geerlingguy.docker
  version: 4.2.1

# Install IdP Shibboleth, fccn stuff
- src: git+https://github.com/fccn/shibboleth-3-4-4-centos7-lite.git
  version: a6802ea65f76ceadf40605aa19a7a05721cb74e7

# Manage iptables
- src: git+https://github.com/fccn/ansible-firewall.git
  version: 0cf719a0899e705b3e5dfe1782c727bb36777c9e

# Utility to deploy apps to docker compose or swarm
- src: git+https://github.com/fccn/ansible-docker-deploy.git
  version: 58f789c637fc78968a2707570327ee4db40a7198

# Auditory of the installed packages and software
- src: git+https://github.com/fccn/ansible_pakiti_client.git
  version: f8edb9c2cfa77d7d075f18eb5bbde7704a20a4e3
