---
# Manage /etc/hosts file
- name: bertvv.hosts
  version: v1.2.0

# Install pip
- name: geerlingguy.pip
  version: 2.1.0

# Install docker
- name: geerlingguy.docker
  src: git+https://github.com/geerlingguy/ansible-role-docker.git
  version: 7.8.0

# Install java
- name: geerlingguy.java
  version: 2.1.0

# Install IdP Shibboleth, fccn stuff
- src: git+https://github.com/fccn/shibboleth-3-4-4-centos7-lite.git
  version: b8541862b35832ab1dd939053b1454d2a716b375

# Manage iptables
- src: git+https://github.com/fccn/ansible-firewall.git
  version: 9c668aa89edc0ffe84a83f194de3975fcb9c92d5

# Utility to deploy apps to docker compose or swarm
- src: git+https://github.com/fccn/ansible-docker-deploy.git
  version: 3d04496a7b4c4cb2654da32d79ee07728364bac3

# Auditory of the installed packages and software
- src: git+https://github.com/fccn/ansible_pakiti_client.git
  version: 2713584acd4de238a39eaf7614092a8ee4a34b4c

# Keepalived to manage Linux Virtual IP addresses for high availability
- src: git+https://github.com/fccn/ansible-keepalived.git
  version: ca1885fe63396020cee5fd7a31827e21b0a51f70

# Rolling deploy role that use iptables to manage load balancer connections
# to a cluster of nodes applying a rolling update strategy
- src: git+https://github.com/fccn/ansible-rolling-deploy.git
  version: 6a17ce53f0c8d5d1403aeb22d712a0ac35104723
