#!/bin/bash -xe
#
# Example
#  ./run-ansible-playbook development deploy.yml --limit balancer_servers --check
#
export LC_ALL='en_US.UTF-8'

# Prepare the secure-nau-data
# clone if not exists and checkout the branch defined on the environment variable `BRANCH_SECURE_DATA`
# or use the default `master` branch
BRANCH_SECURE_DATA="${BRANCH_SECURE_DATA:=master}"
[ -d "nau-data" ] || rm -f nau-data
[ -d "nau-data" ] || git clone -b "${BRANCH_SECURE_DATA}" git@github.com:fccn/secure-nau-data.git nau-data
git -C "nau-data" clean -fdx
git -C "nau-data" pull
git -C "nau-data" checkout ${BRANCH_SECURE_DATA}

# Create the virtual environment
PATH=$HOME/.local/bin:$PATH
uv venv --seed venv -p python3.11
. venv/bin/activate

# Install pip requirements
pip install -r requirements.txt --exists-action w --no-compile --disable-pip-version-check

# Install additional roles from ansible galaxy and directly from git
ansible-galaxy install -p vendor/roles -r requirements.yml --force --ignore-errors

NAU_ENVIRONMENT=$1
shift

HOSTS_FILE="nau-data/envs/${NAU_ENVIRONMENT}/hosts.ini"
test -f $HOSTS_FILE || { echo "Missing hosts file $HOSTS_FILE" ; exit 1; }

ansible-playbook -i $HOSTS_FILE $@
