# Close a server from receiving traffic from load balancer or force VIP swap.
#
# Example - remove a server from cluster:
#   ansible-playbook -i nau-data/envs/<>/hosts.ini server_maintenance.yml -e close=true --limit <server>
#
# Example - readd a server to the cluster:
#   ansible-playbook -i nau-data/envs/<>/hosts.ini server_maintenance.yml -e open=true --limit <server>
---
- hosts: all
  serial: 1 # run update in sequence
  become: True
  gather_facts: True
  vars:
    close: false
    open: false
  pre_tasks:
    - name: Check if 'open' or 'close'
      assert:
        that: (open | bool) or (close | bool)
        fail_msg: You need to open or close
        quiet: true
    - import_tasks: tasks/close_node.yml
      when: (close|bool)
  tasks:
    - import_tasks: tasks/healthcheck.yml
      when: (open|bool)
  post_tasks:
    - import_tasks: tasks/open_node.yml
      when: (open|bool)
