---

- name: Print vars
  hosts: all
  serial: "{{ serial_number | default(1) }}"
  become: True
  gather_facts: True
  tasks:
    - debug:
        var: ansible_interfaces
    - debug:
        var: ansible_all_ipv4_addresses
    - debug: 
        msg: "item: {{  item }} "
      with_items: "{{ ansible_interfaces }}"
