---
mongo_docker_instance_name: mongo
mongo_docker_initdb_root_username: !!null
mongo_docker_initdb_root_password: !!null
mongo_docker_port: 27017

mongo_docker_image: docker.io/mongo:4.2.24
# Older releases:
# docker.io/mongo:4.2.24
# docker.io/mongo:4.0.28
# docker.io/mongo:3.6.23

# From >= 6.0 use mongosh
mongo_shell_command: mongo
# mongo_shell_command: mongosh

mongo_docker_command: "{{ mongo_docker_command_keyfile }}--replSet {{ mongo_docker_replSet }} --port {{ mongo_docker_port }} {{ mongo_docker_command_bind_ip }}"
mongo_docker_command_bind_ip: --bind_ip {{ (mongo_docker_command_bind_ip_default_list + mongo_docker_command_bind_ip_additional_list) | select() | join(',') }}
mongo_docker_command_bind_ip_default_list:
  - localhost
  - "{{ mongo_docker_container_name }}"
  - "{{ ansible_host }}"
mongo_docker_command_bind_ip_additional_list: []
mongo_docker_command_keyfile: "{{ '--keyFile ' + mongo_docker_keyfile_path + ' ' if mongo_docker_keyfile_is_defined | bool else '' }}"
mongo_docker_keyfile_is_defined: "{{ mongo_docker_keyFile_value is defined and ( mongo_docker_keyFile_value | length > 0 ) }}"
mongo_docker_keyfile_path: /run/secrets/mongodb_key

mongo_docker_deploy_parent_folder: /nau/ops
mongo_docker_deploy_base_folder: "{{ mongo_docker_deploy_parent_folder }}/{{ mongo_docker_instance_name }}"
mongo_docker_deploy_compose_template: templates/docker-compose.yml.j2

mongo_docker_container_name: "{{ mongo_docker_deploy_base_folder | basename }}"
mongo_docker_deploy_healthcheck_delay: 5
mongo_docker_deploy_healthcheck_retries: 50

# Files to be templated during deployment
mongo_docker_deploy_templates:
  - src_data: "{{ mongo_docker_initdb_root_username }}"
    dest: "{{ mongo_docker_deploy_base_folder }}/mongo/mongo-root-username"
    secret_name: mongo_root_username
    service: mongo
    docker_target: "{{ mongo_docker_secret_root_username_file_path }}"
    when: "{{ mongo_docker_initdb_root_username | length > 0 }}"
  - src_data: "{{ mongo_docker_initdb_root_password }}"
    dest: "{{ mongo_docker_deploy_base_folder }}/mongo/mongo-root-password"
    secret_name: mongo_root_password
    service: mongo
    docker_target: "{{ mongo_docker_secret_root_password_file_path }}"
    when: "{{ mongo_docker_initdb_root_password | length > 0 }}"
  - src_data: "{{ mongo_docker_keyFile_value }}"
    dest: "{{ mongo_docker_deploy_base_folder }}/mongo/mongodb_key"
    mode: 600
    owner: 999
    secret_name: mongo_key
    service: mongo
    docker_target: "{{ mongo_docker_keyfile_path }}"
    when: "{{ mongo_docker_keyfile_is_defined }}"
  - src: templates/Makefile
    dest: "{{ mongo_docker_deploy_base_folder }}/Makefile"

# File path where the docker secrets are stored inside the mongo docker container
mongo_docker_secret_root_username_file_path: "{{ '/run/secrets/mongo-root-username' if mongo_docker_initdb_root_username else None }}"
mongo_docker_secret_root_password_file_path: "{{ '/run/secrets/mongo-root-password' if mongo_docker_initdb_root_password else None }}"

mongo_docker_volume_path: /data/{{ mongo_docker_instance_name }}

mongo_docker_deploy_extra_hosts: []

mongo_limit_no_file_soft: 65535
mongo_limit_no_file_hard: 65535
