---
# This file contains the ansible variables for the ecommerce-worker service.
# This is not shared with ecommerce, because they are different applications.

openedx_ecommerce_worker_deploy: true
openedx_ecommerce_worker_docker_image: nauedu/openedx-ecommerce-worker:nau-nutmeg.master

openedx_ecommerce_worker_deploy_resources_limit_memory: 500M
openedx_ecommerce_worker_deploy_resources_reservations_memory: 100M

openedx_ecommerce_worker_docker_deploy_files:
  - src: files/ecommerce_worker/nau_production.py
    dest: "{{ openedx_docker_deploy_base_folder }}/ecommerce_worker/nau_production.py"
    service: ecommerce-worker
    config_name: ecommerce_worker_envs_nau_production
    docker_target: /openedx/ecommerce_worker/ecommerce_worker/configuration/nau_production.py

openedx_ecommerce_worker_docker_deploy_templates:
  - src_data:  "{{ openedx_ecommerce_worker_cfg_settings | to_nice_yaml(indent=2, width=1337) }}" # default_flow_style=False didn't work
    dest: "{{ openedx_docker_deploy_base_folder }}/ecommerce_worker/ecommerce_worker.yml"
    service: ecommerce-worker
    config_name: ecommerce_worker_cfg_yml
    docker_target: "{{ ECOMMERCE_WORKER_CFG }}"

openedx_ecommerce_worker_docker_environment_variables: "{{ openedx_ecommerce_worker_docker_environment_variables_default }}"
openedx_ecommerce_worker_docker_environment_variables_default:
  WORKER_CONFIGURATION_MODULE: ecommerce_worker.configuration.nau_production
  ECOMMERCE_WORKER_CFG: "{{ ECOMMERCE_WORKER_CFG }}"

openedx_ecommerce_worker_cfg_settings: "{{ openedx_ecommerce_worker_cfg_settings_default | combine(openedx_ecommerce_worker_cfg_settings_overrides, recursive=True) }}"
openedx_ecommerce_worker_cfg_settings_overrides: {}
openedx_ecommerce_worker_cfg_settings_default:
  BROKER_URL: "{{ ECOMMERCE_BROKER_URL }}"
  JWT_SECRET_KEY: '{{ ECOMMERCE_WORKER_JWT_SECRET_KEY }}'
  JWT_ISSUER: '{{ ECOMMERCE_WORKER_JWT_ISSUER }}'

ECOMMERCE_WORKER_JWT_SECRET_KEY: 'insecure-secret-key'
ECOMMERCE_WORKER_JWT_ISSUER: 'ecommerce_worker'
ECOMMERCE_WORKER_CFG: /openedx/config.yml
