---
openedx_notes_deploy: true
openedx_notes_job_deploy: false
openedx_notes_docker_image: overhangio/openedx-notes:14.0.1
openedx_notes_job_command: ./manage.py migrate

openedx_notes_port: 8000

openedx_notes_docker_deploy_files:
  - src: files/notes/nau_production.py
    dest: "{{ openedx_docker_deploy_base_folder }}/notes/nau_production.py"
    service: notes
    config_name: notes_envs_nau_production
    docker_target: /app/edx-notes-api/notesserver/settings/nau_production.py

openedx_notes_docker_environment_variables: "{{ openedx_notes_docker_environment_variables_default }}"
openedx_notes_docker_environment_variables_default:
  DJANGO_SETTINGS_MODULE: notesserver.settings.nau_production
  # this env variables are loaded by roles/openedx_deploy/files/notes/nau_production.py
  NOTES_SECRET_KEY: "{{ EDX_NOTES_API_SECRET_KEY }}"
  NOTES_HOST: "{{ EDXNOTES_HOSTNAME }}"
  MYSQL_HOST: "{{ openedx_docker_deploy_mysql_default_host }}"
  MYSQL_PORT: "{{ openedx_docker_deploy_mysql_default_port }}"
  NOTES_MYSQL_DATABASE: "{{ EDX_NOTES_API_MYSQL_DB_NAME }}"
  NOTES_MYSQL_USERNAME: "{{ EDX_NOTES_API_MYSQL_DB_USER }}"
  NOTES_MYSQL_PASSWORD: "{{ EDX_NOTES_API_MYSQL_DB_PASS }}"
  ELASTICSEARCH_HOST_PORT: "{{ openedx_docker_deploy_elasticsearch_cluster_hosts_url[0] }}"
  NOTES_OAUTH2_SECRET: "{{ EDX_NOTES_API_CLIENT_SECRET }}"
  NOTES_OAUTH2_ID: "{{ EDX_NOTES_API_CLIENT_ID }}"

EDX_NOTES_API_HOSTNAME: '~^((stage|prod)-)?notes.*'

openedx_notes_nginx_ssl_certificate_docker_target: "{{ openedx_nginx_ssl_certificate_docker_target }}"
openedx_notes_nginx_ssl_certificate_key_docker_target: "{{ openedx_nginx_ssl_certificate_key_docker_target }}"
