---
- name: Deploy
  include_role:
    name: ansible-docker-deploy
  vars:
    docker_deploy_base_folder:         "{{ staticproxy_docker_deploy_base_folder }}"
    docker_deploy_compose_template:    "{{ staticproxy_docker_deploy_compose_template }}"
    docker_deploy_templates:           "{{ staticproxy_docker_deploy_templates | default([]) }}"
    docker_deploy_files:               "{{ staticproxy_docker_deploy_files | default([]) }}"
    docker_deploy_folders_additional:  "{{ staticproxy_docker_deploy_folders_additional | default([]) }}"
    docker_deploy_configs:             "{{ staticproxy_docker_deploy_configs | default([]) }}"
    docker_deploy_secrets:             "{{ staticproxy_docker_deploy_secrets | default([]) }}"
    docker_deploy_services_additional: "{{ staticproxy_docker_deploy_services_additional | default([]) }}"
    docker_deploy_shell: true
    docker_deploy_healthcheck_delay :  "{{ staticproxy_docker_deploy_healthcheck_delay }}"
    docker_deploy_healthcheck_retries: "{{ staticproxy_docker_deploy_healthcheck_retries }}"
  when: staticproxy_docker_deploy_run | default(false)
  tags:
    - docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ staticproxy_docker_deploy_base_folder }}"
  delay: "{{ staticproxy_docker_deploy_healthcheck_delay }}"
  register: result
  until: result.rc == 0
  retries: "{{ staticproxy_docker_deploy_healthcheck_retries }}"
  # run it only when deploying or when on healthcheck mode.
  when: not ansible_check_mode and (staticproxy_docker_deploy_run | default(false)) or (healthcheck | default(false))
  changed_when: False
  tags: 
    - healthcheck
    - docker_deploy

- name: Check URLs
  include_role:
    name: nau_check_urls
  vars:
    nau_urls_to_check: "{{ staticproxy_nau_urls_to_check }}"
  when: (staticproxy_docker_deploy_run | default(false)) or (healthcheck | default(false))
  tags:
    - docker_deploy
    - nau_check_urls
