---
- name: Deploy
  include_role:
    name: ansible-docker-deploy
  vars:
    docker_deploy_base_folder:         "{{ coursecertificate_docker_deploy_base_folder }}"
    docker_deploy_compose_template:    "{{ coursecertificate_docker_deploy_compose_template }}"
    docker_deploy_templates:           "{{ coursecertificate_docker_deploy_templates | default([]) }}"
    docker_deploy_files:               "{{ coursecertificate_docker_deploy_files | default([]) }}"
    docker_deploy_folders_additional:  "{{ coursecertificate_docker_deploy_folders_additional | default([]) }}"
    docker_deploy_configs:             "{{ coursecertificate_docker_deploy_configs | default([]) }}"
    docker_deploy_secrets:             "{{ coursecertificate_docker_deploy_secrets | default([]) }}"
    docker_deploy_services_additional: "{{ coursecertificate_docker_deploy_services_additional | default([]) }}"
    docker_deploy_shell: true
    docker_deploy_healthcheck_delay :  "{{ coursecertificate_docker_deploy_healthcheck_delay }}"
    docker_deploy_healthcheck_retries: "{{ coursecertificate_docker_deploy_healthcheck_retries }}"
  when: coursecertificate_docker_deploy_run | default(false)
  tags:
    - docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ coursecertificate_docker_deploy_base_folder }}"
  delay: "{{ coursecertificate_docker_deploy_healthcheck_delay }}"
  register: result
  until: result.rc == 0
  retries: "{{ coursecertificate_docker_deploy_healthcheck_retries }}" # 20 minutes of waiting
  # run it only when deploying or when on healthcheck mode.
  when: not ansible_check_mode and (coursecertificate_docker_deploy_run | default(false)) or (healthcheck | default(false))
  changed_when: False
  tags: 
    - healthcheck
    - docker_deploy

- name: Check URLs
  include_role:
    name: nau_check_urls
  vars:
    nau_urls_to_check: "{{ coursecertificate_nau_urls_to_check }}"
  when: (coursecertificate_docker_deploy_run | default(false)) or (healthcheck | default(false))
  tags:
    - docker_deploy
    - nau_check_urls
