---
staticproxy_docker_deploy_compose_template: templates/docker-compose.yml.j2
staticproxy_docker_deploy_base_folder: /nau/ops/staticproxy

staticproxy_docker_deploy_compose_name: "{{ staticproxy_docker_deploy_base_folder | basename }}"

staticproxy_docker_deploy_templates:
  - src: "{{ staticproxy_makefile_template | default('templates/Makefile') }}"
    dest: "{{ staticproxy_docker_deploy_base_folder }}/Makefile"
  - src: "{{ staticproxy_nginx_conf_template | default('templates/nginx.conf') }}"
    dest: "{{ staticproxy_docker_deploy_base_folder }}/nginx/nginx.conf"
    docker_target: /etc/nginx/nginx.conf
    config_name: nginx_conf
    service: nginx

staticproxy_nginx_ssl_certificate_folder: "{{ COMMON_PATH_CUSTOM_FILES }}/static/ssl"
staticproxy_nginx_enable_https: true
staticproxy_nginx_proxy_protocol: true
staticproxy_nginx_hsts_max_age: 31536000
staticproxy_nginx_http2: true
staticproxy_nginx_image: docker.io/nginx:1.22.1
staticproxy_nginx_http_ingress_port:  22080
staticproxy_nginx_https_ingress_port: 22443

staticproxy_nginx_admin_access_trusted_ip_cidrs: "{{ NGINX_TRUSTED_IP_CIDRS }}"

staticproxy_docker_deploy_files: "{{ staticproxy_docker_deploy_files_default + staticproxy_docker_deploy_files_additional }}"
staticproxy_docker_deploy_files_additional: []
staticproxy_docker_deploy_files_default:
  - src: "{{ staticproxy_nginx_ssl_certificate_key }}"
    dest: "{{ staticproxy_docker_deploy_base_folder }}/nginx/ssl/certificate.key.pem"
    docker_target: "{{ staticproxy_nginx_docker_ssl_certificate_key }}"
    secret_name: certificate_key
    service: nginx
  - src: "{{ staticproxy_nginx_ssl_certificate_crt }}"
    dest: "{{ staticproxy_docker_deploy_base_folder }}/nginx/ssl/certificate.crt.pem"
    docker_target: "{{ staticproxy_nginx_docker_ssl_certificate_crt }}"
    secret_name: certificate_crt
    service: nginx

staticproxy_nginx_ssl_certificate_key: !!null
staticproxy_nginx_ssl_certificate_crt: !!null
staticproxy_nginx_docker_ssl_certificate_key: /etc/ssl/certs/certificate.key.pem
staticproxy_nginx_docker_ssl_certificate_crt: /etc/ssl/certs/certificate.crt.pem

# Nginx is only a reverse proxy to reach the buckets that need public access with or without signature
staticproxy_nginx_servers: "{{ staticproxy_nginx_servers_default }}"
staticproxy_nginx_servers_default:
  - name: "shared.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ NAU_SHARED_BUCKET }}/"
  - name: "{{ EDXAPP_GRADE_BUCKET }}.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ EDXAPP_GRADE_BUCKET }}/"
  - name: "profile-pictures.{{ nau_ceph_host_public}}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ NAU_PROFILE_IMAGE_BUCKET }}/"
  - name: "uploads.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ EDXAPP_AWS_STORAGE_BUCKET_NAME }}/"
  - name: "{{ EDXAPP_IMPORT_EXPORT_BUCKET }}.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ EDXAPP_IMPORT_EXPORT_BUCKET }}/"
  - name: "{{ EDXAPP_AWS_STORAGE_BUCKET_NAME }}.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ EDXAPP_AWS_STORAGE_BUCKET_NAME }}/"
  - name: "{{ RICHIE_NAU_AWS_BUCKET_NAME }}.{{ nau_ceph_host_public }}"
    proxy_pass: "https://{{ nau_ceph_host }}/{{ RICHIE_NAU_AWS_BUCKET_NAME }}/"

# List of URLs to check during deployment.
staticproxy_nau_urls_to_check:
  - name: staticproxy maintenance page
    host: "shared.{{ nau_ceph_host_public }}"
    protocol: https
    page: maintenance-site/index.html
    content: ajuda.nau.edu.pt
    retries: 5
    port: "{{ staticproxy_nginx_https_ingress_port }}"
    haproxy_protocol: true

staticproxy_docker_deploy_healthcheck_retries: 120
staticproxy_docker_deploy_healthcheck_delay: 60
