---
- name: Create build folder
  file:
    path: "{{ build_web_server_docker_file | dirname }}"
    state: directory
    recurse: true
    mode: '0755'
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  tags:
    - build_web_server
    - docker_deploy

- name: Template docker image
  template:
    src: "{{ build_web_server_dockerfile_template }}"
    dest: "{{ build_web_server_docker_file }}"
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  tags:
    - build_web_server
    - docker_deploy

- name: Pull docker target image
  docker_image:
    name: "{{ build_web_server_docker_image_target }}"
    source: pull
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  tags:
    - build_web_server
    - docker_deploy

# Use manually the `docker image build` command because the ansible `docker_image` doesn't support
# the docker buildkit. 
# Reference: 
# - https://github.com/docker/docker-py/issues/2230
# - https://github.com/ansible-collections/community.general/issues/514
# The docker buildkit has better build time performance for multi stage parallel builds.
- name: Build web server docker image
  shell: DOCKER_BUILDKIT=1 docker image build --tag {{ build_web_server_docker_repository }}/{{ build_web_server_docker_image }}:{{ build_web_server_docker_tag }} - < {{ build_web_server_docker_file }}
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  tags:
    - build_web_server
    - docker_deploy

- name: Login into docker registry
  docker_login:
    registry_url: "{{ docker_registry_url | default(omit) }}"
    username: "{{ docker_registry_username }}"
    password: "{{ docker_registry_password }}"
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  changed_when: false
  when: docker_registry_username is defined and docker_registry_password is defined
  tags:
    - build_web_server
    - docker_deploy

- name: Push web server docker image to docker repository
  docker_image:
    name: "{{ build_web_server_docker_repository }}/{{ build_web_server_docker_image }}"
    tag: "{{ build_web_server_docker_tag }}"
    push: "{{ build_web_server_push }}"
    source: local
  register: docker_image_build_result
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  tags:
    - build_web_server
    - docker_deploy

- name: Logout of docker registry
  docker_login:
    registry: "{{ docker_registry | default(omit) }}"
    username:
    state: absent
  delegate_to: "{{ build_web_server_node }}"
  run_once: true
  changed_when: false
  when: docker_registry_username is defined and docker_registry_password is defined
  tags:
    - build_web_server
    - docker_deploy
