---
build_web_server_services: []

# The docker image that will be used to built
build_web_server_docker_image_target: docker.io/nginx:1.24.0

build_web_server_docker_file: "/tmp/build_web_server/{{ build_web_server_docker_repository }}/{{ build_web_server_docker_image }}/{{ build_web_server_docker_tag }}/Dockerfile"

build_web_server_dockerfile_template: templates/Dockerfile

build_web_server_node: "{{ inventory_hostname }}"

build_web_server_push: "{{ docker_registry_username is defined and docker_registry_password is defined }}"

build_web_server_docker_registry: docker.io
build_web_server_docker_image_out: "{{ build_web_server_docker_registry }}/{{ build_web_server_docker_repository }}/{{ build_web_server_docker_image }}:{{ build_web_server_docker_tag }}"
