---
- name: Install make
  package:
    name: make
    state: present
  tags:
    - docker_deploy

- name: Deploy
  include_role:
    name: ansible-docker-deploy
  vars:
    docker_deploy_base_folder:         "{{ clickhouse_docker_deploy_base_folder }}"
    docker_deploy_compose_template:    "{{ clickhouse_docker_deploy_compose_template }}"
    docker_deploy_templates:           "{{ clickhouse_docker_deploy_templates | default([]) }}"
    docker_deploy_files:               "{{ clickhouse_docker_deploy_files | default([]) }}"
    docker_deploy_folders_additional:  "{{ clickhouse_docker_deploy_folders_additional | default([]) }}"
    docker_deploy_configs:             "{{ clickhouse_docker_deploy_configs | default([]) }}"
    docker_deploy_secrets:             "{{ clickhouse_docker_deploy_secrets | default([]) }}"
    docker_deploy_services_additional: "{{ clickhouse_docker_deploy_services_additional | default([]) }}"
    docker_deploy_shell: true
    docker_deploy_healthcheck_verify_retries: "{{ clickhouse_docker_deploy_healthcheck_verify_retries }}"
    docker_deploy_healthcheck_verify_delay:   "{{ clickhouse_docker_deploy_healthcheck_verify_delay }}"
  tags:
    - docker_deploy

- name: Run healthcheck
  shell: make healthcheck
  args:
    chdir: "{{ clickhouse_docker_deploy_base_folder }}"
  delay: "{{ clickhouse_docker_deploy_healthcheck_verify_delay }}"
  register: result
  until: result.rc == 0
  retries: "{{ clickhouse_docker_deploy_healthcheck_verify_retries }}"
  # run it only when deploying or when on healthcheck mode.
  changed_when: False
  when: not ansible_check_mode
  tags: 
    - healthcheck
    - docker_deploy
