- name: Print HaProxy update certs commands stdout
  debug:
    msg: "{{ hostvars[inventory_hostname][variable_to_print].stdout_lines }}"
  when: hostvars[inventory_hostname][variable_to_print].stdout_lines is defined
  tags: haproxy_update_certs

- name: Print HaProxy update certs commands stderr
  debug:
    msg: "{{ hostvars[inventory_hostname][variable_to_print].stderr_lines }}"
  when: hostvars[inventory_hostname][variable_to_print].stderr_lines is defined and ( hostvars[inventory_hostname][variable_to_print].stderr_lines | length > 0 )
  tags: haproxy_update_certs

