---
- name: Define certificate file name
  set_fact:
    certificate_file_name: "{{ domain_config['cert-name'] | default(domain_config.domain) }}"
  tags: haproxy_update_certs

# Add certificate and its key to HaProxy at runtime using unix socket
- name: Add new certificates to HaProxy
  shell: echo "new ssl cert /certs/{{ certificate_file_name }}.pem" | {{ socat_cmd }}
  args:
    executable: /bin/bash
  register: haproxy_socat_output
  tags: haproxy_update_certs

- name: Print variable
  include_tasks: print_stdout_and_stderr.yml
  vars:
    variable_to_print: haproxy_socat_output
    stdout_contains_string: Certificate
  tags: always

- name: Add certificates to HaProxy
  shell: 'echo -e "set ssl cert /certs/{{ certificate_file_name }}.pem <<\n$(cat {{ docker_deploy_base_folder }}/certs/{{ certificate_file_name }}.pem {{ docker_deploy_base_folder }}/certs/{{ certificate_file_name }}.pem.key)\n" | {{ socat_cmd }}'
  args:
    executable: /bin/bash
  register: haproxy_socat_output
  tags: haproxy_update_certs

- name: Print variable
  include_tasks: print_stdout_and_stderr.yml
  vars:
    variable_to_print: haproxy_socat_output
    stdout_contains_string: Transaction created for certificate
  tags: always

# - name: Add certificate keys to HaProxy
#   shell: echo -e "set ssl cert /certs/{{ certificate_file_name }}.pem.key <<\n$(cat ./certs/{{ certificate_file_name }}.pem.key)\n" | {{ socat_cmd }}
#   loop: "{{ acme_domains_to_issue_certs }}"
#   loop_control:
#     loop_var: domain
#   register: haproxy_socat_output
  
# - name: Print
  # include_tasks: print_stdout_and_stderr.yml

- name: Add certificate keys to HaProxy - commit changes
  shell: echo "commit ssl cert /certs/{{ certificate_file_name }}.pem" | {{ socat_cmd }}
  args:
    executable: /bin/bash
  register: haproxy_socat_output
  tags: haproxy_update_certs
  
- name: Print variable
  include_tasks: print_stdout_and_stderr.yml
  vars:
    variable_to_print: haproxy_socat_output
    stdout_contains_string: Success!
  tags: always

- name: Show certificate details on HaProxy
  shell: echo "show ssl cert /certs/{{ certificate_file_name }}.pem" | {{ socat_cmd }}
  args:
    executable: /bin/bash
  register: haproxy_socat_output
  tags: haproxy_update_certs

- name: Print variable
  include_tasks: print_stdout_and_stderr.yml
  vars:
    variable_to_print: haproxy_socat_output
    stdout_contains_string: "Subject: /CN={{ domain_config.domain }}"
  tags: always
